version: '3'

services:

  php:
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/sing-a-song-kata
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
